export const ROUTE_PATHS = {
  DASHBOARD: '/',
  CAMPANHA: '/campanha',
  NOVA_CAMPANHA: '/campanha/nova',
  CENAS: '/campanha/cenas',
  NOVA_CENA: '/campanha/cenas/nova',
  NPCS: '/npcs',
  NOVO_NPC: '/npcs/novo',
  CRIATURAS: '/criaturas',
  NOVA_CRIATURA: '/criaturas/nova',
  MAPAS: '/mapas',
  NOVO_MAPA: '/mapas/novo',
  MISSOES: '/missoes',
  NOVA_MISSAO: '/missoes/nova',
  CARDFLUX: '/cardflux',
  NOVO_BARALHO: '/cardflux/novo',
  CARDFLUX_CARTAS: '/cardflux/cartas',
  NOVA_CARTA: '/cardflux/cartas/nova',
  NOTAS: '/notas',
  NOVA_NOTA: '/notas/nova',
};

export const PAGE_TITLES = {
  [ROUTE_PATHS.DASHBOARD]: 'Dashboard',
  [ROUTE_PATHS.CAMPANHA]: 'Campanha',
  [ROUTE_PATHS.NOVA_CAMPANHA]: 'Nova Campanha',
  [ROUTE_PATHS.CENAS]: 'Cenas',
  [ROUTE_PATHS.NOVA_CENA]: 'Nova Cena',
  [ROUTE_PATHS.NPCS]: 'NPCs',
  [ROUTE_PATHS.NOVO_NPC]: 'Novo NPC',
  [ROUTE_PATHS.CRIATURAS]: 'Criaturas',
  [ROUTE_PATHS.NOVA_CRIATURA]: 'Nova Criatura',
  [ROUTE_PATHS.MAPAS]: 'Mapas',
  [ROUTE_PATHS.NOVO_MAPA]: 'Novo Mapa',
  [ROUTE_PATHS.MISSOES]: 'Missões',
  [ROUTE_PATHS.NOVA_MISSAO]: 'Nova Missão',
  [ROUTE_PATHS.CARDFLUX]: 'CardFlux',
  [ROUTE_PATHS.NOVO_BARALHO]: 'Novo Baralho',
  [ROUTE_PATHS.CARDFLUX_CARTAS]: 'Cartas do Baralho',
  [ROUTE_PATHS.NOVA_CARTA]: 'Nova Carta',
  [ROUTE_PATHS.NOTAS]: 'Notas',
  [ROUTE_PATHS.NOVA_NOTA]: 'Nova Nota',
};
