export const ROUTE_PATHS = {
  DASHBOARD: '/',
  CAMPANHA: '/campanha',
  NOVA_CAMPANHA: '/campanha/nova',
  CENAS: '/campanha/cenas',
  NOVA_CENA: '/campanha/cenas/nova',
  NPCS: '/npcs',
  NPC_CLONE: '/npcs/clonar',
  JOGADORES: '/jogadores',
  JOGADOR_CLONE: '/jogadores/clonar',
  CRIATURAS: '/criaturas',
  CRIATURA_CLONE: '/criaturas/clonar',
  MAPAS: '/mapas',
  NOVO_MAPA: '/mapas/novo',
  MISSOES: '/missoes',
  NOVA_MISSAO: '/missoes/nova',
  CARDFLUX: '/cardflux',
  CARDFLUX_CARTAS: '/cardflux/cartas',
  LUTA: '/luta',
  NOTAS: '/notas',
  NOVA_NOTA: '/notas/nova',
};

export const PAGE_TITLES = {
  [ROUTE_PATHS.DASHBOARD]: 'Dashboard',
  [ROUTE_PATHS.CAMPANHA]: 'Campanha',
  [ROUTE_PATHS.NOVA_CAMPANHA]: 'Nova Campanha',
  [ROUTE_PATHS.CENAS]: 'Cenas',
  [ROUTE_PATHS.NOVA_CENA]: 'Nova Cena',
  [ROUTE_PATHS.NPCS]: 'NPCs',
  [ROUTE_PATHS.NPC_CLONE]: 'Clone de NPC',
  [ROUTE_PATHS.JOGADORES]: 'Jogadores',
  [ROUTE_PATHS.JOGADOR_CLONE]: 'Clone de Jogador',
  [ROUTE_PATHS.CRIATURAS]: 'Criaturas',
  [ROUTE_PATHS.CRIATURA_CLONE]: 'Clone de Criatura',
  [ROUTE_PATHS.MAPAS]: 'Mapas',
  [ROUTE_PATHS.NOVO_MAPA]: 'Novo Mapa',
  [ROUTE_PATHS.MISSOES]: 'Missões',
  [ROUTE_PATHS.NOVA_MISSAO]: 'Nova Missão',
  [ROUTE_PATHS.CARDFLUX]: 'CardFlux',
  [ROUTE_PATHS.CARDFLUX_CARTAS]: 'Cartas do Baralho',
  [ROUTE_PATHS.LUTA]: 'Luta',
  [ROUTE_PATHS.NOTAS]: 'Notas',
  [ROUTE_PATHS.NOVA_NOTA]: 'Nova Nota',
};
